server:
  port: 8282
spring:
  datasource:
    url: jdbc:mysql://115.159.98.166:3306/chinese-gang?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: B8Ft4g?z2TgI
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
app:
  appid: "wx316be3df54cf177d"
  secret: "2a3ea94ea5ed6dde088468fb7874191b"
  imageURL: "http://115.159.98.166"
yll:
  APP_KEY: "c33bd86351174a049f4b65c1a9a51fc1"
  uid: "Men_api001"
  url: "http://115.159.98.166/globe_api/public"
